# Generated by Django 4.0.6 on 2022-07-09 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 13, 57, 15, 8126, tzinfo=utc)),
        ),
    ]
