# Generated by Django 4.0.6 on 2022-07-09 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_done_alter_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 13, 57, 38, 370751, tzinfo=utc)),
        ),
    ]
