# Generated by Django 4.0.6 on 2022-07-09 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 14, 42, 3, 37816, tzinfo=utc)),
        ),
    ]
