# Generated by Django 4.0.6 on 2022-07-09 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 17, 27, 47, 194598, tzinfo=utc)),
        ),
    ]
